// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(function() {
    $.pluginName = function(element, options) {
      var setState;
      this.defaults = {
        message: 'hellow word',
        callback: function() {}
      };
      this.state = '';
      this.settings = {};
      this.$element = $(element);
      setState = function(state) {
        this.state = state;
      };
      this.getState = function() {
        return state;
      };
      this.getSetting = function(settingKey) {
        return this.settings[settingKey];
      };
      this.callSettingFunction = function(functionName) {
        return this.settings[functionName]();
      };
      this.init = function() {
        this.settings = $.extend({}, this.defaults, options);
        return this.settings.callback(element, this.settings.message);
      };
      return this.init();
    };
    return $.fn.pluginName = function(options) {
      return this.each(function() {
        var plugin;
        if (void 0 === ($(this)).data('pluginName')) {
          plugin = new $.pluginName(this, options);
          return ($(this)).data('pluginName', plugin);
        }
      });
    };
  });

}).call(this);
